model:
  type: LSTM  
  parameters:
    input_size: 1
    num_outputs: 10
    hidden_size: 64
    num_layers: 2  
    rnn_type: lstm  
    device: cpu  
    hidden_noise_std: 0.0  
    dropout_input: False 
    drop_prob: 0.2  