name: Neural-Decoding
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.12
  - numpy>=1.26
  - pandas>=2.0.0
  - pyyaml>=6.0.2
  - scipy>=1.15
  - scikit-learn>=1.6
  - omegaconf>=2.3.0
  - hydra-core>=1.3.2
  - matplotlib>=3.10
  - tqdm
  - pynwb
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio