preprocessing_trainer:
  order: [dict1, stabilization1, split1, add_history1, add_history2, normalize_sequence, normalize_standard, tuple_out]
  #order: [dict1, stabilization1, split1, tuple_out]
  content:
    dict1:
      type: Dict2DataDictBlock
      params:
        neural_type: tcfr
    split1:
      type: DataSplitBlock
      params:
        split_ratio: 0.9
        split_seed: -1
    add_history1:
      type: AddHistoryBlock
      params:
        location: ['neural_train', 'finger_train']
        seq_length: 8
        isRR: True
    add_history2:
      type: AddHistoryBlock
      params:
        location: ['neural_test', 'finger_test']
        seq_length: 8
        isRR: True
    normalize_sequence:
      type: UpdateNormalizationBlock
      params:
        location: ['neural_train', 'neural_test']
        method: sklearn
        normalizer_params:
          type: StandardScaler
          is_save: False
          params: {}
    normalize_standard:
      type: UpdateNormalizationBlock
      params:
        location: ['finger_train', 'finger_test']
        method: sklearn
        normalizer_params:
          type: StandardScaler
          is_save: True
          save_path: "results/normalizers/finger_standard_scaler.pkl"
          params: {}
    # add_noise:
    #   type: AddNoiseBlock
    #   params:
    #     location: ['neural_train']
    #     noise_params:
    #       bias_neural_std: 0.2
    #       noise_neural_std: 0.1
    #       device: cuda
    tuple_out:
      type: Dict2TupleBlock
      params: {}
    stabilization1:
      type: StabilizationBlock
      params:
        location: 'neural'
        stabilization_config:
          type: LatentSpaceAlignment
          params:
            # dim_red_method: 
            #   type: EMFactorAnalysis1
            #   params:
            #     verbose: True
            dim_red_method: 
              type: NoDimRed
              params: {}
            alignment_method: 
              type: NoAlignment
              params: {}
            fpath: "results/alignment_models/latent_space_alignment_date_{date}.pkl"
            ndims: 60
    