preprocessing_trainer:
  order: [dict1, split1, add_history1, normalize_sequence, normalize_standard, tensor1, tuple_out]
  content:
    dict1:
      type: Dict2DataDictBlock
      params:
        neural_type: sbp
    split1:
      type: DataSplitBlock
      params:
        split_ratio: 0.9
        split_seed: -1
    add_history1:
      type: AddHistoryBlock
      params:
        location: ['neural_train', 'neural_test']
        seq_length: 20
    normalize_sequence:
      type: UpdateNormalizationBlock
      params:
        location: ['neural_train', 'neural_test']
        method: sequence_scaler
        normalizer_params:
          is_save: False
    normalize_standard:
      type: UpdateNormalizationBlock
      params:
        location: ['finger_train', 'finger_test']
        method: sklearn
        normalizer_params:
          type: StandardScaler
          is_save: True
          save_path: "cache/normalizers/finger_standard_scaler.pkl"
          params: {}
    tensor1:
      type: EnforceTensorBlock
      params:
        device: cuda
        dtype: float32
    # add_noise:
    #   type: AddNoiseBlock
    #   params:
    #     location: ['neural_train']
    #     noise_params:
    #       bias_neural_std: 0.2
    #       noise_neural_std: 0.1
    #       device: cuda
    tuple_out:
      type: Dict2TupleBlock
      params: {}
    