type: zstruct
date: ???
runs: ???
server_path: "Z:/Data/Monkeys"
institution: "University of Michigan"
lab: "Chestek Lab"
subject: ???
is_monkey: true
data_path: null
xpc:
  behavior_field: "FingerAnglesTIMRL"
  behavior_name: "finger_positions"
  behavior_description: "Finger flexion position [thumb, index, middle, ring, pinky], from fully extended (0) to fully flexed (1)"
  behavior_unit: "flexion units"
  behavior_comments: "Raw position data"
  signal_field: "NeuralFeature"
  signal_name: "emg"
  signal_description: "Mean absolute value of EMG"
  signal_conversion: 2.5e-7
  signal_filtering: "bandpass: 100-500 Hz"
  signal_comments: "Mean Absolute Value, for each 1ms bin"
  experiment_time_field: "ExperimentTime"
  spikes_exist: false
  spikes_field: "Channel"
  spikes_name: "spikes"
  num_channels: 16
  device: 
    name: "Cerebus"
    description: "Data acquisition system"
    manufacturer: "Blackrock Neurotech"
  electrode_group:
    name: "emg_electrodes"
    description: "EMG electrodes"
    location: "XXX"
nwb:
  compression:
    type: "gzip"
    options: 4
  save: true



