type: zstruct
date: ???
runs: ???
server_path: "Z:/Data/Monkeys"
institution: "University of Michigan"
lab: "Chestek Lab"
subject: ???
is_monkey: true
data_path: null
xpc:
  behavior_field: "FingerAnglesTIMRL"
  behavior_name: "finger_positions"
  behavior_description: "Finger flexion position [thumb, index, middle, ring, pinky], from fully extended (0) to fully flexed (1)"
  behavior_unit: "flexion units"
  behavior_comments: "Raw position data"
  signal_field: "NeuralFeature"
  signal_name: "brain"
  signal_description: "Spiking band power of brain activity"
  signal_conversion: 2.5e-7
  signal_filtering: "bandpass: 300-1000 Hz"
  signal_comments: "Spiking Band Power (SBP) - i.e. the Mean Absolute Value, for each 1ms bin"
  experiment_time_field: "ExperimentTime"
  spikes_exist: true
  spikes_field: "Channel"
  spikes_name: "spikes"
  num_channels: 96
  device: 
    name: "Utah Array"
    description: "Utah Array"
    manufacturer: "Blackrock Neurotech"
  electrode_group:
    name: "Utah Array"
    description: "Utah Array"
    location: "XXX"
nwb:
  compression:
    type: "gzip"
    options: 4
  save: true



