model:
  name: "RidgeRegression" # Names defined in model module
  parameters:
    alpha: 0.001
    fit_intercept: False # arbitrary parameters feeding into the model
  input_shape: [1, 769] # input shape in list
  output_shape: [1,4] # output shape in list

fpath: "examples/decoder/models/ridge_regression_model.pkl" # directory to saved model