model:
  type: LSTM  
  parameters:
    input_size: 96
    num_outputs: 4
    hidden_size: 64
    num_layers: 2  
    rnn_type: lstm  
    device: cpu  
    hidden_noise_std: 0.0  
    dropout_input: False 
    drop_prob: 0.2  

optimizer:
  type: Adam
  params:
    lr: 0.001
    weight_decay: 0.0001

scheduler:
  type: StepLR
  params:
    step_size: 50
    gamma: 0.4472

loss_func:
  type: MSELoss
  params: {}

training:
  num_epochs: 2
  batch_size: 32
  device: cpu # cuda , if avail 
  print_results: True
  print_every: 5

data:
  data_path: "tests/trainer/data/sub-Monkey-N_ses-20200127_ecephys.nwb"
  params:
    num_train_trials: 300
    split_ratio: 0.8
    split_seed: 42
    sequence_length: 5